### ISSUE TITLE
<RK⚡️ issue={3} /> - Thursday, Oct 10

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/react-knowledgeable-talks#12]
- 🗓 Date: Thursday, October 10
- 🗺 Venue: SP Digital
- 🦄 Host: @thchia 
- 🔖 RSVP: https://www.meetup.com/React-Knowledgeable/events/264767450/

## `<RK />` this month

To propose a talk, [create an issue here](https://github.com/react-knowledgeable/talks/issues/new?assignees=&labels=event&template=event.md&title=%3CRK+%2F%3E+%23+-+date) and reference **this issue**.

Agenda
---
- **19:00** Door opens and chills
- **19:30** ⚛ React this month #17 
- **19:40** First 3 talks
- **20:15** Networking break
- **20:30** Last 2 talks && talks from the ground
- **21:00** Go home

**Comment by yeokm1** [comment]
Video of Thomas's talk: https://engineers.sg/v/3710

**Comment by wgao19** [comment]
Thank you! @yeokm1 Great collaboration!
