### ISSUE TITLE
<RK⚡️ issue={2} /> Thursday, Sept 5

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/react-knowledgeable-talks#9]
- 🗓 Date: Sept 5, 2019
- 🗺 Venue: Hackerspace SG, 344B King George’s Avenue
- 🦄 Host: @wgao19 

## `<RK />` this month

This month, we have our magic girl [@bokukage](https://mobile.twitter.com/bokukage) on a hooks talk about her drawing moon walk and duck walk on a screen. It's super cool you absolutely have to see this.

We'll also have a mysterious friend (hint: you may know him! or her!) to join us with a cool sharing on the topic of open source.

And we hope to hear more from **YOU**. To propose a talk, [create an issue here](https://github.com/react-knowledgeable/talks/issues/new?assignees=&labels=event&template=event.md&title=%3CRK+%2F%3E+%23+-+date) and reference this issue (#9).

Agenda
---
- **19:00** Door opens and chills
- **19:30** ⚛ React this month #10 
- **19:40** First 3 talks
  + 👞 Dancing with React Hooks #2
  + 🦖 How Modern Static Site Generators Work #11
  + 💄 Build a Gatsby Theme and publish #13 
- **20:15** Question break
  + 👥 Are React and CSS Friends? #14
- **20:30** Last 2 talks && talks from the ground
- **21:00** Go home

**Comment by valentine** [comment]
@wgao19 Venue needs to be edited! 💥

**Comment by thchia** [comment]
Edited, thanks @valentine!
